# Generated by Django 4.1.2 on 2022-10-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comments_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='blog_post',
        ),
    ]
